// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID      int64
	Owner   string
	Balance int64
	// can be negative or positive
	Currency  string
	CreatedAt time.Time
}

type Entry struct {
	ID        int32
	AccountID int64
	// must be positive
	Amount    int64
	CreatedAt sql.NullTime
}

type Transfer struct {
	ID            int64
	FromAccountID int64
	ToAccountID   int64
	Amount        int64
	CreatedAt     time.Time
}
