apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::385792460968:role/simplebank-github-actions-role
      username: simplebank-github-actions-role
      groups:
        - system:masters